# Site settings
title: Covariance Structure Models
heading: Covariance Structure Models
email: farouni.1@osu.edu
url: http://rfarouni.github.io/PSYCH7821
baseurl: ""
description: "Welcome to the Course Website for PSYCH 7821 (AU2016)"


# List of links in the navigation bar
navbar-links:
  Assignments: "assignments"
  Resources: "resources"


# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Rick Farouni
  location: Course Developed at
  social: Links
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: slack
    url: https://psych7821.slack.com
  - title: canvas
    url: https://osu.instructure.com/courses/6811
  - title: github
    url: https://github.com/rfarouni/PSYCH7821

# Postal address (add as many lines as necessary)
address:
  - line: The Department of Psychology
  - line: The Ohio State University
  - line: Columbus, Ohio.

# Credits content
credits: The website uses the Freelancer open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
